export interface DataKegiatan {
  id?: number;
  tahun?: number | null;
  Kode_UK?: string | null;
  Nama_Unit_Kerja?: string | null;
  Jenis?: "Rawat Jalan" | "Rawat Inap" | "Operatif" | "Non Layanan" | null;
  // 1. Utilisasi Bahan Medis
  Resep_Lembar_Resep?: number | null;
  // 2. Utilisasi Bahan Non Medis
  Cucian_kg_Cucian?: number | null;
  Makanan_Karyawan_jml_Porsi?: number | null;
  Makanan_Pasien_jml_Porsi?: number | null;
  // 3. Utilisasi Penunjang (Set dan Instrumen)
  Instrumen_Besar?: number | null;
  Instrumen_Sedang?: number | null;
  Instrumen_Kecil?: number | null;
  Set_Pack_Besar?: number | null;
  Set_Pack_Sedang?: number | null;
  Set_Pack_Kecil?: number | null;
  // 4. Utilisasi Pegawai
  SDM_dokter?: number | null;
  SDM_Perawat?: number | null;
  SDM_Non?: number | null;
  Jml_jam_Praktek_Harian?: number | null;
  // 5. Utilisasi Daya
  Listrik_kwh?: number | null;
  Air_m3?: number | null;
  Telepon_Freq_pakai_per_titik?: number | null;
  Komputer_simrs_user?: number | null;
  // 6. Utilitas Tempat Tidur
  Tempat_Tidur_SVIP?: number | null;
  Tempat_Tidur_VIP?: number | null;
  Tempat_Tidur_I?: number | null;
  Tempat_Tidur_II?: number | null;
  Tempat_Tidur_III?: number | null;
  Tempat_Tidur_Khusus?: number | null;
  // 7. Kunjungan & Pelayanan
  Kunjungan_Pasien_Lama?: number | null;
  Kunjungan_Pasien_Baru?: number | null;
  Jumlah_Tindakan?: number | null;
  // 8. Utilitas Perawatan
  Hari_Rawat_SVIP?: number | null;
  Hari_Rawat_VIP?: number | null;
  Hari_Rawat_I?: number | null;
  Hari_Rawat_II?: number | null;
  Hari_Rawat_III?: number | null;
  // 9. Diklat/Pelatihan
  Diklat_Jumlah_Siswa?: number | null;
  Diklat_Lama_Hari?: number | null;
  // Computed fields (generated by DB)
  Jumlah_SDM?: number | null;
  Total_Kunjungan_Pasien?: number | null;
  Total_Diklat?: number | null;
  Jumlah_Hari_Rawat?: number | null;
  created_at?: string;
  updated_at?: string;
}

export interface DataKegiatanInsert extends Omit<DataKegiatan, 'id' | 'created_at' | 'updated_at'> {}
export interface DataKegiatanUpdate extends Partial<DataKegiatanInsert> {}
